import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/home/header";
import Footer from "@/components/home/footer";
import { StoreProvider } from "@/providers/redux";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Pokemon Next",
  description: "Generated by OAB",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${redHatDisplay.className} antialiased`}>
        <StoreProvider>
          <main className="container grid grid-rows-[auto_1fr_auto] min-h-screen mx-auto">
            <Header />
            {children}
            <Footer />
          </main>
        </StoreProvider>
      </body>
    </html>
  );
}
